//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popcorn.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Popcorn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actors.
        /// </summary>
        public static string ActorsLabel {
            get {
                return ResourceManager.GetString("ActorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string AllLabel {
            get {
                return ResourceManager.GetString("AllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Animes.
        /// </summary>
        public static string AnimesLabel {
            get {
                return ResourceManager.GetString("AnimesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Buffering.
        /// </summary>
        public static string BufferingLabel {
            get {
                return ResourceManager.GetString("BufferingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string CollectionsLabel {
            get {
                return ResourceManager.GetString("CollectionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm password....
        /// </summary>
        public static string ConfirmPasswordWatermark {
            get {
                return ResourceManager.GetString("ConfirmPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You seem to have an internet connection error. Please retry..
        /// </summary>
        public static string ConnectionErrorDescriptionPopup {
            get {
                return ResourceManager.GetString("ConnectionErrorDescriptionPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internet connection error.
        /// </summary>
        public static string ConnectionErrorTitlePopup {
            get {
                return ResourceManager.GetString("ConnectionErrorTitlePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Currently playing.
        /// </summary>
        public static string CurrentlyPlayingLabel {
            get {
                return ResourceManager.GetString("CurrentlyPlayingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directors.
        /// </summary>
        public static string DirectorsLabel {
            get {
                return ResourceManager.GetString("DirectorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloading subtitles....
        /// </summary>
        public static string DownloadingSubtitlesLabel {
            get {
                return ResourceManager.GetString("DownloadingSubtitlesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download limit (kB/s).
        /// </summary>
        public static string DownloadLimitLabel {
            get {
                return ResourceManager.GetString("DownloadLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email....
        /// </summary>
        public static string EmailWatermark {
            get {
                return ResourceManager.GetString("EmailWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à That&apos;s embarrassing....
        /// </summary>
        public static string EmbarrassingError {
            get {
                return ResourceManager.GetString("EmbarrassingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No movie found.
        /// </summary>
        public static string EmptySearchLabel {
            get {
                return ResourceManager.GetString("EmptySearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A critical error has occured. You should restart the app immediately..
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Favorites.
        /// </summary>
        public static string FavoritesTitleTab {
            get {
                return ResourceManager.GetString("FavoritesTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name....
        /// </summary>
        public static string FirstNameWatermark {
            get {
                return ResourceManager.GetString("FirstNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Genres.
        /// </summary>
        public static string GenresLabel {
            get {
                return ResourceManager.GetString("GenresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greatest.
        /// </summary>
        public static string GreatestTitleTab {
            get {
                return ResourceManager.GetString("GreatestTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last name....
        /// </summary>
        public static string LastNameWatermark {
            get {
                return ResourceManager.GetString("LastNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Later.
        /// </summary>
        public static string LaterLabel {
            get {
                return ResourceManager.GetString("LaterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading trailer....
        /// </summary>
        public static string LoadingTrailerLabel {
            get {
                return ResourceManager.GetString("LoadingTrailerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality.
        /// </summary>
        public static string MovieQualityLabel {
            get {
                return ResourceManager.GetString("MovieQualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string MovieSettingsLabel {
            get {
                return ResourceManager.GetString("MovieSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Movies.
        /// </summary>
        public static string MoviesLabel {
            get {
                return ResourceManager.GetString("MoviesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à movies.
        /// </summary>
        public static string MoviesWord {
            get {
                return ResourceManager.GetString("MoviesWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new update has been applied. Would you like to restart now?.
        /// </summary>
        public static string NewUpdateDescriptionLabel {
            get {
                return ResourceManager.GetString("NewUpdateDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New update.
        /// </summary>
        public static string NewUpdateLabel {
            get {
                return ResourceManager.GetString("NewUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Now.
        /// </summary>
        public static string NowLabel {
            get {
                return ResourceManager.GetString("NowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Off.
        /// </summary>
        public static string OffLabel {
            get {
                return ResourceManager.GetString("OffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à of.
        /// </summary>
        public static string OfWord {
            get {
                return ResourceManager.GetString("OfWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On.
        /// </summary>
        public static string OnLabel {
            get {
                return ResourceManager.GetString("OnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password....
        /// </summary>
        public static string PasswordWatermark {
            get {
                return ResourceManager.GetString("PasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Playing.
        /// </summary>
        public static string PlayingTitleTab {
            get {
                return ResourceManager.GetString("PlayingTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play.
        /// </summary>
        public static string PlayLabel {
            get {
                return ResourceManager.GetString("PlayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Popular.
        /// </summary>
        public static string PopularTitleTab {
            get {
                return ResourceManager.GetString("PopularTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rating.
        /// </summary>
        public static string RatingLabel {
            get {
                return ResourceManager.GetString("RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent.
        /// </summary>
        public static string RecentTitleTab {
            get {
                return ResourceManager.GetString("RecentTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reload.
        /// </summary>
        public static string ReloadLabel {
            get {
                return ResourceManager.GetString("ReloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search....
        /// </summary>
        public static string SearchBoxWatermark {
            get {
                return ResourceManager.GetString("SearchBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string SearchTitleTab {
            get {
                return ResourceManager.GetString("SearchTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seen.
        /// </summary>
        public static string SeenTitleTab {
            get {
                return ResourceManager.GetString("SeenTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string SettingsMenuTitle {
            get {
                return ResourceManager.GetString("SettingsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shows.
        /// </summary>
        public static string ShowsLabel {
            get {
                return ResourceManager.GetString("ShowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subtitles.
        /// </summary>
        public static string SubtitlesLabel {
            get {
                return ResourceManager.GetString("SubtitlesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trailer.
        /// </summary>
        public static string TrailerButton {
            get {
                return ResourceManager.GetString("TrailerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The trailer is not available for the current language..
        /// </summary>
        public static string TrailerNotAvailable {
            get {
                return ResourceManager.GetString("TrailerNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Release informations:.
        /// </summary>
        public static string UpdateReleasesInformationsLabel {
            get {
                return ResourceManager.GetString("UpdateReleasesInformationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload limit (kB/s).
        /// </summary>
        public static string UploadLimitLabel {
            get {
                return ResourceManager.GetString("UploadLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username....
        /// </summary>
        public static string UsernameWatermark {
            get {
                return ResourceManager.GetString("UsernameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Watch.
        /// </summary>
        public static string WatchButton {
            get {
                return ResourceManager.GetString("WatchButton", resourceCulture);
            }
        }
    }
}
